package:
  name: py3-numpy-2.0
  version: 2.0.2
  epoch: 0
  description: The fundamental package for scientific computing with Python.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provider-priority: 0

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

vars:
  pypi-package: numpy

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - cython
      - gfortran
      - git
      - meson
      - openblas-dev
      - py3-supported-pip
      - py3-supported-python-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/numpy/numpy
      tag: v${{package.version}}
      expected-commit: 854252ded83e6b9c21c4ee80558d354d8a72484c
      recurse-submodules: true

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-${{vars.major-minor-version}}
    description: ${{vars.pypi-package}}-${{vars.major-minor-version}} installed for python${{range.key}}
    pipeline:
      - runs: python${{range.key}} -m pip install . "--root=${{targets.contextdir}}" --prefix=/usr
      - runs: |
          # Remove tests that have windows-specific portions that always fail
          # distutils is removed in 3.12+ and therefore the files won't be found, hence -f
          rm -f ${{targets.contextdir}}/usr/lib/python${{range.key}}/site-packages/numpy/distutils/tests/test_mingw32ccompiler.py
          rm -f ${{targets.contextdir}}/usr/lib/python${{range.key}}/site-packages/numpy/distutils/tests/test_system_info.py
      - uses: strip
    dependencies:
      runtime:
        - py${{range.key}}-pygments
      # Intentionally disabled for now to ensure a smooth migration
      #provides:
      #  - py${{range.key}}-${{vars.pypi-package}}-${{vars.major-minor-version}}
      #  - numpy
      provider-priority: ${{range.value}}
    test:
      environment:
        contents:
          packages:
            - git
            - meson
            - py${{range.key}}-pytest
            - py${{range.key}}-pip
            - py${{range.key}}-meson
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import numpy
        - runs: |
            pip${{range.key}} install hypothesis
            python${{range.key}} -c "import numpy, sys; sys.exit(numpy.test() is False)"
        - runs: |
            git clone --branch v${{package.version}} https://github.com/numpy/numpy.git py${{range.key}}-numpy
            cd py${{range.key}}-numpy/numpy
            cp -r tests ../..
            cd ../../tests
            python${{range.key}} -m pytest . -k "not test_api_importable" -k "not test_configtool"

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-${{vars.major-minor-version}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}-${{vars.major-minor-version}}
      provides:
        - f2py
        - numpy-config
      provider-priority: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}-${{vars.major-minor-version}}/usr/bin ${{targets.contextdir}}/usr
    test:
      pipeline:
        - runs: f2py -v
        - runs: numpy-config -v
        - runs: |
            git clone --branch v${{package.version}} https://github.com/numpy/numpy.git py${{range.key}}-numpy
            cd py${{range.key}}-numpy/numpy
            cp -r tests ../..
            cd ../../tests
            python${{range.key}} -m pytest . -k "not test_api_importable"

  - name: py3-supported-${{vars.pypi-package}}-${{vars.major-minor-version}}
    description: meta package providing ${{vars.pypi-package}}-${{vars.major-minor-version}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}-${{vars.major-minor-version}}
        - py3.11-${{vars.pypi-package}}-${{vars.major-minor-version}}
        - py3.12-${{vars.pypi-package}}-${{vars.major-minor-version}}
        - py3.13-${{vars.pypi-package}}-${{vars.major-minor-version}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    tag-filter-prefix: v2.0
    strip-prefix: v
    strip-suffix: .dev0
